apiVersion: "spec.keptn.sh/0.2.3"
kind: "Shipyard"
metadata:
  name: "notes-app-cicd"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "delivery"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "direct"
                # Indicate that Helm is used for deployment
                deploytool: "helm"
            - name: "test"
              properties:
                teststrategy: "functional"
            - name: "evaluation"
              properties:
                timeframe: "5m"
        - name: "rollback"
          tasks:
            - name: "rollback"
              triggeredOn:
                - result: "fail"
                  selector:
                    match:
                      task: "evaluation"

    - name: "staging"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "dev.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
                # Indicate that Helm is used for deployment
                deploytool: "helm"
            - name: "test"
              properties:
                teststrategy: "performance"
            - name: "evaluation"
              properties:
                timeframe: "10m"
        - name: "rollback"
          tasks:
            - name: "rollback"
              triggeredOn:
                - result: "fail"
                  selector:
                    match:
                      task: "evaluation"

    - name: "production"
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: "staging.delivery.finished"
          tasks:
            - name: "deployment"
              properties:
                deploymentstrategy: "blue_green_service"
                # Indicate that Helm is used for deployment
                deploytool: "helm"
            - name: "release"
              properties:
                strategy: "manual"
        - name: "rollback"
          tasks:
            - name: "rollback"
              triggeredOn:
                - result: "fail"
                  selector:
                    match:
                      task: "release"
